Sistema_Reserva_Alquiler_Habi/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Sistema_Reserva_Alquiler_Habi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult _Nosotros()
        {

            return View();
        }


    }
}

Sistema_Reserva_Alquiler_Habi/Controllers/NosotrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sistema_Reserva_Alquiler_Habi.Controllers
{
    public class NosotrosController : Controller
    {
        // GET: Nosotros
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sistema_Reserva_Alquiler_Habi/Controllers/_NosotrosController.cs
using Sistema_Reserva_Alquiler_Habi.Models;
using System.Web.Mvc;

namespace Sistema_Reserva_Alquiler_Habi.Controllers
{
    public class _NosotrosController : Controller
    {
        private ReservaAlquilerEntities db = new ReservaAlquilerEntities();

        // GET: _Nosotros
        public ActionResult Index()
        {
            return View();
        }


    }
}

Sistema_Reserva_Alquiler_Habi/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Hotel de Pandas</p>

Sistema_Reserva_Alquiler_Habi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sistema_Reserva_Alquiler_Habi/Views/Home/Index.cshtml
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Multipager Template- Travelic </title>
    <!--REQUIRED STYLE SHEETS-->
    @Styles.Render("~/template/css")


</head>
<body>
    <!-- NAV SECTION -->
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <a class="navbar-brand"><img src="~/Content/img/lo.png" width="120" /></a>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Create", "Consultas")</li>
                    <li>@Html.ActionLink("Nosotros", "_Nosotros", "Home")</li>

                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Reservas", "Create", "Reservas")</li>
                    }



                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Categorias", "Index", "Categorias")</li>
                    }

                    <li>@Html.ActionLink("Piso", "Index", "Pisoes")</li>
                    @Html.Partial("_LoginPartial")
                </ul>

            </div>


        </div>
    </div>
    <!--END NAV SECTION -->
    <!--HOME SECTION-->
    <div id="home-sec">

        
            
     
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-12">

                        <span class="head-main">Panda Hotel<img  src="~/Content/img/p.png" aling="left" width="90"/>                             </span>


                    </div>
                </div>
            </div>

        </div>


        <section id="services-sec">
            <div class="container">
                <div class="row ">
                    <div class="text-center g-pad-bottom">
                        <div class="col-md-4 col-sm-4 alert-info">
                            <h4>Reserve con confianza</h4>
                            <p>
                                Somos concientes de la importancia de la flexibilidad cuando entra en juego la planificación de viajes en el futuro,
                                y queremos que confíe en nosotros cuando haga una reserva.
                            </p>

                        </div>
                        <div class="col-md-4 col-sm-4 alert-success">
                            <h4>Fantásticas ofertas </h4>
                            <p>
                                Comprendemos que, a la hora de planificar los futuros viajes, se necesita flexibilidad.
                                Puede reservar con confianza, sabiendo que nuestras políticas de cancelación flexible se adaptarán a sus necesidades.
                            </p>

                        </div>

                        <div class="col-md-4 col-sm-4 alert-danger">
                            <h4> Salud y seguridad </h4>
                            <p>
                                En respuesta a la pandemia de COVID-19, nos hemos asociado con los mejores expertos para implementar
                                nuevos estándares de seguridad y protocolos y procedimientos operativos y garantizar su seguridad.
                            </p>

                        </div>
                    </div>
                </div>


                <div class="row go-marg">
                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <h4 class="adjst" align="center"> Habitación Individual </h4>
                                <p>

                                    <img src="~/Content/img/Habitaciones/habi10.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Una habitación asignada a una persona.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>

                                </p>

                            </div>
                        </div>
                    </div>


                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <h4 class="adjst" align="center"> Habitación Doble </h4>
                                <p>
                                    <img src="~/Content/img/Habitaciones/habi6.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Una habitación asignada a dos personas.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>
                                </p>

                            </div>
                        </div>

                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <h4 class="adjst" align="center">Habitación triple</h4>
                                <p>
                                    <img src="~/Content/img/Habitaciones/habi11.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Con capacidad para tres personas.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>
                                </p>

                            </div>
                        </div>

                    </div>
                </div>


                <div class="row go-marg">
                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <h4 class="adjst" align="center"> Habitación King </h4>
                                <p>
                                    <img src="~/Content/img/Habitaciones/habit7.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Una habitación con una cama king-size. Puede ser ocupado por una o más personas.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>
                                </p>

                            </div>
                        </div>
                    </div>


                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">

                            <div class="panel-body">
                                <h4 class="adjst" align="center"> Suite Ejecutiva </h4>
                                <p>
                                    <img src="~/Content/img/Habitaciones/habi12.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Una habitación con uno o más dormitorios y una sala de estar separada.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>
                                </p>

                            </div>
                        </div>
                    </div>


                    <div class="col-md-4 col-sm-4">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <h4 class="adjst" align="center"> Suite Presidencial </h4>
                                <p>
                                    <img src="~/Content/img/Habitaciones/habi14.jpg" height="300" width="330" style="border: 2px solid; color: black;" />
                                    <b>Inclye uno o más dormitorios, una sala de estar bien decorada y los suministros.</b>
                                    <br />
                                    Equipamiento de la habitación:
                                    <br />
                                    - Aire acondicionado
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10" >
                                            <input type="submit" class="btn btn-default" value="Más detalles" />
                                        </div>
                                    </div>
                                </p>

                            </div>
                        </div>
                    </div>


                </div>




            </div>

        </section>

       
        <!-- END FOOTER SECTION -->
        @Scripts.Render("~/template/js")

</body>
</html>

Sistema_Reserva_Alquiler_Habi/Views/Home/_Nosotros.cshtml
@{
    ViewBag.Title = "Nosotros";
}

<h2 align="center">Nosotros somos amigues hace 4 años</h2>



<div class="container">
    <div class="row ">
        <div class="text-center g-pad-bottom">



            <div class="row go-marg">
                <div class="col-md-4 col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h4 class="adjst" align="center"> <b> Maria Cuenca </b> </h4>
                            <p>
                                <img src="~/Content/img/Bios/Mari.PNG" width="230" class="img-rounded" /><br />
                                <br />Edad:  23 años
                                <br /> de Santa Elena - Cordillera
                                <br /> Actualmente vive en San Lorenzo
                                <br />estudiante del 4to año de Ingenieria en Informatica
                                Octavo semestre
                                <br />Hobbies:
                                Cantar ,
                                Cocinar ,
                                Enseñar Matematicas, Físicas,
                                Programar no es su pasion pero aprende.
                                <br />

                            </p>

                        </div>
                    </div>
                </div>



                <div class="col-md-4 col-sm-4">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <h4 class="adjst" align="center"> <b> Patricia Lezcano </b> </h4>
                            <p>
                                <img src="~/Content/img/Bios/Mabe.jpg" width="310" class="img-rounded" />
                                <br /> Edad:  22 años
                                <br />Reside en a ciudad de Capiata
                                <br />Estudiante del 4to año de Ingenieria en Informatica
                                Octavo semestre
                                <br /> Hobbies:
                                Dibujar,
                                Leer,
                                Ver series,
                                Jugar VideoJuegos
                                <br />

                            </p>

                        </div>
                    </div>
                </div>




                <div class="col-md-4 col-sm-4">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <h4 class="adjst" align="center"> <b>Edgar Gonzalez </b> </h4>
                            <p>
                                <img src="~/Content/img/Bios/e.jpg" class="img-rounded" width="290" />
                                <br /> Edad:  24 años
                                <br /> Reside en a ciudad de San Lorenzo
                                <br /> Estudiante del 4to año de Ingenieria en Informatica
                                <br /> Octavo semestre
                                <br /> Hobbies:
                                Jugar deportes,
                                Le gusta diseñar
                                <br />

                            </p>

                        </div>
                    </div>
                </div>
            </div>


            <div class="row go-marg" align="center">
                <div class="col-md-4 col-sm-4">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <h4 class="adjst" align="center"> <b> Angel Aquino </b> </h4>
                            <p>
                                <img src="~/Content/img/Bios/Angel.jpeg" width="330" class="img-rounded" />
                                <br /> Edad:  21 años
                                <br />Reside en a ciudad de Ñemby - San Antonio
                                <br /> Estudiante del 4to año de Ingenieria en Informatica
                                Octavo semestre
                                <br />Hobbies:
                                Compartir con amigos,
                                Jugar Play,
                                Comer
                                <br />

                            </p>

                        </div>
                    </div>
                </div>


                <div class="col-md-4 col-sm-4">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <h4 class="adjst" align="center"> <b>Leandro Portillo </b> </h4>
                            <p>
                                <img src="~/Content/img/Bios/Lean.jpeg" width="330" class="img-rounded" />
                                <br />Edad:  22 años
                                <br />Reside en a Argentina - Buenos Aires
                                <br />Estudiante del 4to año de Ingenieria en Informatica
                                Octavo semestre
                                <br /> Hobbies:
                                Jugar al Futboll,
                                Escuchar Musica
                                <br />

                            </p>

                        </div>
                    </div>
                </div>
            </div>


        </div>




    </div>


</div>
  